### ISSUE TITLE
The inferred type of 'vitePlugin' cannot be named

### ISSUE THREAD

**Issue by tangdaoyuan** [tangdaoyuan/unplugin-keep-polite#21]
### Describe the bug

```bash
Entry module "src/index.ts" is using named and default exports together. Consumers of your bundle will have to use `chunk["default"]` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning
src/index.ts(30,14): error TS2742: The inferred type of 'vitePlugin' cannot be named without a reference to '../playground/node_modules/vite/dist/node'. This is likely not portable. A type annotation is necessary.

Error building /Users/tangdaoyuan/git/front_end/plugin_stack/unplugin-keep-polite: Error: Failed to compile. Check the logs above.
Error: Failed to compile. Check the logs above.
    at error (file:///Users/tangdaoyuan/git/front_end/plugin_stack/unplugin-keep-polite/node_modules/.pnpm/rollup@2.77.2/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at throwPluginError (file:///Users/tangdaoyuan/git/front_end/plugin_stack/unplugin-keep-polite/node_modules/.pnpm/rollup@2.77.2/node_modules/rollup/dist/es/shared/rollup.js:21764:12)
    at Object.error (file:///Users/tangdaoyuan/git/front_end/plugin_stack/unplugin-keep-polite/node_modules/.pnpm/rollup@2.77.2/node_modules/rollup/dist/es/shared/rollup.js:22486:20)
    at Object.error (file:///Users/tangdaoyuan/git/front_end/plugin_stack/unplugin-keep-polite/node_modules/.pnpm/rollup@2.77.2/node_modules/rollup/dist/es/shared/rollup.js:21941:42)
    at Object.transform (file:///Users/tangdaoyuan/git/front_end/plugin_stack/unplugin-keep-polite/node_modules/.pnpm/rollup-plugin-dts@4.2.2_oo3i3f3qmqiztdz5qgxrrjmd5e/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1590:26)
    at file:///Users/tangdaoyuan/git/front_end/plugin_stack/unplugin-keep-polite/node_modules/.pnpm/rollup@2.77.2/node_modules/rollup/dist/es/shared/rollup.js:22695:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  id: '/Users/tangdaoyuan/git/front_end/plugin_stack/unplugin-keep-polite/src/index.ts',
  hook: 'resolveId',
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs--resolver',
  watchFiles: [
    '/Users/tangdaoyuan/git/front_end/plugin_stack/unplugin-keep-polite/src/index.ts'
  ]
}
```

### Reproduction

pnpm run build

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 3.75 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Safari: 15.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tangdaoyuan/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tangdaoyuan** [comment]
fixed at v0.2.1+
